name: Automated API tests gragh

on: workflow_dispatch

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY_GRAPH }}
      - name: Run API tests
        run: |
          postman collection run 42342525-bd1340df-c6d8-4b06-9527-b10a91ef4962 -e 42342525-f621a73e-f222-48a5-a64b-db085f039461
      # - name: Save test Results
      #   run: |
      #    postman collection run 42342525-bd1340df-c6d8-4b06-9527-b10a91ef4962 -e 42342525-f621a73e-f222-48a5-a64b-db085f039461 --reporters=json --reporter-json-export=postman-report.json
      # - name: Check for failed status codes
      #   run: |
      #     echo "Checking API response codes..."
      #     cat postman-report.json | jq ".run.executions[].response.code"
      #     if cat postman-report.json | jq -e '.run.executions[].response.code | tostring | select(. | test("^[^2|3]"))' > /dev/null; then
      #       echo "❌ API test failed: Found response codes outside 2xx or 3xx range."
      #       exit 1
      #     else
      #       echo "✅ All API tests passed successfully."
      #     fi  
