name: Automated API tests using Postman CLI

on: workflow_dispatch

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "18042228-96a52346-19a3-4b5b-86a4-a285015754f4" -e "18042228-5943a5be-8a17-4140-b6bd-c8b60ae2b80a"

      - name: Check for failed status codes
        run: |
          echo "Checking API response codes..."
          # cat postman-report.json | jq ".run.executions[].response.code"
          if jq -e '.run.executions[].response.code | select(. < 200 or . >= 400)' json_report.json > /dev/null; then
            echo "❌ API test failed: Found response codes outside 200-300 range."
            exit 1
          else
            echo "✅ All API tests passed successfully."
          fi          
